export const COMMERCIAL_EXPERIENCE = [
  {
    id: 1,
    nameComapany: "DeveloArt",
    positionJob: "Frontend Developer",
    startJob: "SEPTEMBER 2022",
    endJob: "JUNE 2023",
    description:
      "Creating a restaurant management mobile application in React Native.",
    responsibilities: [
      "Creating screens and views for the application",
      "Writing application logic",
      "Fetching data from the backend",
      "Conducting code reviews.",
      "Participating in meetings (weekly).",
    ],
    technologies: [
      "React Native",
      "Next.js +13",
      "TypeScript",
      "JavaScript",
      "Redux Toolkit",
      "CSS3",
    ],
  },
  {
    id: 2,
    nameComapany: "ART-Tech Solutions",
    positionJob: "Frontend Developer",
    startJob: "JUNE 2023",
    endJob: "PRESENT",
    description:
      "Creating several portals for the Alivi Foundation in Next.js and React",
    responsibilities: [
      "Rewriting code from React to Next.js.",
      "Creating new functionalities in Next.js.",
      "Creating new functionalities in React.",
      "Integrating with the backend.",
      "Code optimization.",
      "Daily meetings.",
      "Enhance the SEO.",
      "Introducing simplified logic.",
    ],
    technologies: [
      "React.js",
      "Next.js +13",
      "TypeScript",
      "JavaScript",
      "Redux Toolkit",
      "RTK Query",
      "Bootstrap 5",
      "SCSS",
    ],
  },
  {
    id: 3,
    nameComapany: "Freelancer",
    positionJob: "Fullstack Developer",
    startJob: "FEBRUARY 2024",
    endJob: "PRESENT",
    description:
      "Creating website about rating companies in Next.js and Node.js",
    responsibilities: [
      "Creating endpoints",
      "Server and database configuration",
      "Management",
      "Creating UI and implementing them in Next.js",
    ],
    technologies: [
      "Next.js +13",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind",
      "Jira",
      "Figma",
    ],
  },
];
